spring.application.name=auth_service

spring.datasource.url=${MYSQL_PUBLIC_URL}
# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Server Port (Optional)
server.port=${PORT:9090}

# JWT Secret
jwt.secret=${JWT_SECRET:thisismysecretkeywhichisusedforgeneratingthejwttokensinthisapplicationmysecretkey123456}
jwt.expiration=3600000


spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USER:printfkarimulla@gmail.com}
spring.mail.password=${MAIL_PASS:kstb lnjw amsr njyo}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.test-connection=false


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


